CREATE TABLE IF NOT EXISTS PRODUCTS (
PRODUCT_ID TEXT,
PRODUCT_NAME TEXT,
SUPPLIER_ID TEXT,
CATEGORY_ID TEXT,
UNIT TEXT,
PRICE REAL
);

INSERT INTO PRODUCTS(PRODUCT_ID, PRODUCT_NAME, SUPPLIER_ID, CATEGORY_ID, UNIT, PRICE) VALUES
('1', 'CHAIS', '1', '1', '10 boxes * 20 bags', 18),
('2', 'salt', '1', '1', '101  * 20 bags', 19),
('3', 'pepper', '1', '2', '120 boxes bags', 20),
('4', 'idk', '2', '2', '100 boxes', 21),
('5', 'balls', '2', '3', '1900 bags', 6.9);
SELECT COUNT(PRODUCT_ID) AS PRODUCT_COUNT
FROM PRODUCTS;
SELECT AVG(PRICE) AS AVERAGE_PRICE
FROM PRODUCTS;

SELECT SUM(PRICE) AS TOTAL_PRICE
FROM PRODUCTS;
